spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/matcheasy
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    encoding: UTF-8
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true


#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/
#      add-mappings: true



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

security:
  jwt:
    accessToken:
      secret-key: accesskeybymatcheasy