spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matcheasy?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    encoding: UTF-8
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true


#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath:/static/
#      add-mappings: true



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
    encoding:
      force-response: true

security:
  jwt:
    accessToken:
      secret-key: accesskeybymatcheasy